import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const SECTIONS = [
  {
    title: "Acceptance",
    body: [
      "By installing the GrapeRoot Review GitHub App or accessing review.graperoot.dev, you agree to these Terms. If you do not agree, uninstall the App and discontinue use.",
    ],
  },
  {
    title: "Description of service",
    body: [
      "GrapeRoot Review posts automated code review comments on GitHub pull requests. Findings are generated by a large-language model and cross-referenced against the repository's import graph. They are advisory — not a substitute for human review.",
      "The service is provided as-is. We reserve the right to modify, suspend, or discontinue features at any time.",
    ],
  },
  {
    title: "Your responsibilities",
    body: [
      "You must have the right to install the App on any repository you add — either as an owner or with owner authorisation.",
      "You must not use the service to review code you do not have permission to access.",
      "You are responsible for any actions taken on the basis of AI-generated review comments.",
    ],
  },
  {
    title: "Intellectual property",
    body: [
      "GrapeRoot Review and its graph-analysis technology are proprietary to GrapeRoot. Your code and review comments remain yours.",
      "We do not claim any ownership over code submitted for review.",
    ],
  },
  {
    title: "Paid plans",
    body: [
      "Pro plan fees are billed monthly per user seat. Seats are counted as GitHub users who open pull requests on connected repositories.",
      "Subscriptions auto-renew until cancelled. Cancellation takes effect at the end of the current billing period — no partial refunds.",
      "We reserve the right to change pricing with 30 days' notice.",
    ],
  },
  {
    title: "Limitation of liability",
    body: [
      "To the maximum extent permitted by law, GrapeRoot is not liable for any indirect, incidental, or consequential damages arising from use of the service, including missed bugs or incorrect review suggestions.",
      "Our total liability to you in any month will not exceed the fees paid in that month.",
    ],
  },
  {
    title: "Termination",
    body: [
      "You may terminate at any time by uninstalling the GitHub App.",
      "We may terminate or suspend your access for violation of these Terms, with or without notice.",
    ],
  },
  {
    title: "Governing law",
    body: [
      "These Terms are governed by the laws of India. Disputes will be resolved in the courts of Bengaluru, Karnataka.",
    ],
  },
  {
    title: "Contact",
    body: [
      "Questions: hello@graperoot.dev",
    ],
  },
];

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen pt-24 pb-20 px-4 sm:px-6">
        <div className="max-w-2xl mx-auto">
          <p className="text-xs font-semibold text-grape-400 uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-3xl sm:text-4xl font-bold text-white tracking-tight mb-3">Terms of Service</h1>
          <p className="text-zinc-400 text-sm mb-2">Effective date: 18 May 2026</p>
          <p className="text-zinc-400 text-sm mb-12 leading-relaxed">
            These Terms govern your use of GrapeRoot Review, operated by GrapeRoot.
            Please read them carefully before installing or using the service.
          </p>

          <div className="flex flex-col gap-10">
            {SECTIONS.map(({ title, body }) => (
              <section key={title}>
                <h2 className="text-base font-semibold text-white mb-3">{title}</h2>
                <div className="flex flex-col gap-2">
                  {body.map((para, i) => (
                    <p key={i} className="text-sm text-zinc-400 leading-relaxed">{para}</p>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
